# pre-commit Git hook script configuration
#
# See: https://pre-commit.com/

repos:
  - # Format code
    repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - # Apply linting rules
    repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - # Enforce documentation
    repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        exclude: ^tests
  - # Sort imports
    repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
